version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15432:5432"
    volumes:
      - /Desktop/dev/docker/volumes/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "rm92073@fiap.com.br"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge